version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:80"
      - "5173:5173"
    volumes:
      - .:/var/www/html
    networks:
      - lamp-net
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myblog
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - lamp-net

volumes:
  mysql-data:

networks:
  lamp-net:
